### ISSUE TITLE
expected indentation of 1 characters but found 0

### ISSUE THREAD

**Issue by transedward** [sindresorhus/eslint-config-xo-react#1]
my .eslintrc

{
  "extends": ["xo/esnext", "xo-react"],
  "env": {
  "browser": true,
  "mocha": true,
  "node": true
  }
}

and I indent with tab using atom, not sure what's going on here?

**Comment by transedward** [comment]
sample code:

```js
export default class MyComponent extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      source: '',
      brief: ''
    };
  }
}
```

from the line starts with super until brief, keep throwing error

and also a file just containing
```js
export default {
  home: { // throwing error from here, the whole file
    path: '/',
    method: 'get',
```

**Comment by sindresorhus** [comment]
You probably used space indentation while the default are tabs. ESLint has since improved that error message.
