### ISSUE TITLE
Reconsider jsx-filename-extension rule.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/eslint-config-xo-react#11]
Forcing use of the `.jsx` extension causes problems with AVA. JSX can be composed with other transforms that might encourage other file extensions (`.es6`, `.ts`, etc). The rule just really doesn't seem to add any value that I can see.

**Comment by sindresorhus** [comment]
Agreed. I added it before having read https://github.com/airbnb/javascript/pull/985#issuecomment-239145468.
