### ISSUE TITLE
Probably inconsistent rules

### ISSUE THREAD

**Issue by ythecombinator** [sindresorhus/eslint-config-xo-react#15]
Whenever I try to run `xo` via my terminal or via the one from VS Code I get the following error:

```
Error: /path/to/my/repo/node_modules/eslint-config-xo-react/index.js:
	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].noSortAlphabetically" has additional properties.
	Value "data["0"].reservedFirst" has additional properties.
```

as you can see here:

<img width="889" alt="captura de tela 2017-07-05 as 01 17 02" src="https://user-images.githubusercontent.com/2644563/27849025-3c295440-6120-11e7-9d3c-6264dc67e72d.png">

and here:

<img width="1102" alt="captura de tela 2017-07-05 as 01 20 10" src="https://user-images.githubusercontent.com/2644563/27849037-4be01a04-6120-11e7-8976-79cf99743069.png">

I'm still not sure if this is a problem with this package: it seems to be something with [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) itself–but the only issue I found (https://github.com/yannickcr/eslint-plugin-react/issues/1267) sound a bit inconclusive for me.

My setup is:

```json
{
  ...
  "devDependencies": {
    ...
    "eslint": "^4.1.1",
    "eslint-config-xo": "^0.18.2",
    "eslint-config-xo-react": "^0.13.0",
    "eslint-plugin-react": "^3.16.1",
    "xo": "^0.18.2",
    "xo-loader": "^0.8.0"
  },
  ...
  "xo": {
    "extends": "xo-react"
  }
}

```

just like recommended on the docs.

**Comment by vadimdemedes** [comment]
Could you try downgrading to `eslint@3` and see if the error is gone?

**Comment by ythecombinator** [comment]
Just triad doing what you suggested @vadimdemedes but I couldn't get any different result 😢

**Comment by vadimdemedes** [comment]
In case your repo is public, could you link to it, so that we can try to reproduce it?

**Comment by vadimdemedes** [comment]
I also missed the fact that you have both `xo` **and** `eslint`, wondering if that could have something to do with this error. Unlikely though.

**Comment by kevva** [comment]
Could you try updating `eslint-plugin-react` to `7.1.0`? `3.16.1` is really, really outdated.

**Comment by vadimdemedes** [comment]
I bet @kevva is right, I just assumed that deps were near-latest.

**Comment by ythecombinator** [comment]
Thanks for the attention and fast feedback from both of you, @vadimdemedes and @kevva 😄  –and sorry for the delay on answering 😭 

It turns out that @kevva was right and I hadn't payed enough attention to `npm-check` alert about `eslint-plugin-react`–sorry, such a quite dumb mistake of mine.

Everything's ok now.
