### ISSUE TITLE
React DOM variables are shown with no-unused-vars error

### ISSUE THREAD

**Issue by saneef** [sindresorhus/eslint-config-xo-react#3]
I used xo to lint this file.
 
```jsx
'use strict';

let React = require('react');
let ReactDom = require('react-dom');

let Hello = React.createClass({
	render: function () {
		return <div>Hello {this.props.name}</div>;
	}
});

ReactDom.render(
	<Hello name="World" />,
	document.getElementById('container')
);
```
But I'm getting this error, `6:5  error  "Hello" is defined but never used  no-unused-vars`. Isn't the Hello is used? Or, am I configuring some thing wrong?

Here is my config from package.json:
```
  "xo": {
    "envs": [
      "node",
      "browser",
      "es6"
    ]
  },
  "eslintConfig": {
    "extends": ["xo", "xo-react"]
  },
```

**Comment by saneef** [comment]
I have a feeling I'm doing something very dumb here. `eslint-config-xo-react` to be used with the `xo`; that is directly with eslint?

**Comment by saneef** [comment]
Hey guys sorry for the trouble. That was very dumb of me. When I used with eslint, everything working.

**Comment by sindresorhus** [comment]
Use the XO `extends` option.

**Comment by saneef** [comment]
Oh. Great it worked. Thanks @sindresorhus
