### ISSUE TITLE
Linter errors when not using Webpack neither SystemJS

### ISSUE THREAD

**Issue by micaelmbagira** [sindresorhus/eslint-config-xo-react#6]
I have a React/Typescript app and I inject scripts on classic way in `index.html`.
The linter reports many issues like `Cannot find name 'React'` or `JSX element type 'MyType' is not a constructor function for JSX elements`...
However these errors are not there when I use webpack or systemjs.

Here is my package.json:
````json
"eslintConfig": {  
    "extends": [
      "xo-space/esnext",
      "xo-react"
    ]
}
````

**Comment by sindresorhus** [comment]
Look up the rules in https://github.com/yannickcr/eslint-plugin-react and you'll see why they're violations. No idea why there's a difference when you use Webpack.

**Comment by micaelmbagira** [comment]
Well, the problem is not about the violations. For instance when I have `<Title/>` in my JSX template, the linter throws `'Title' is not defined` while this piece of code is correct...
