### ISSUE TITLE
Use space instead tab for indent

### ISSUE THREAD

**Issue by zckrs** [sindresorhus/eslint-config-xo-react#7]
Hi,

What tab are used ? Maybe because eslint-config-xo use tab too

But can we create a repo/fork `eslint-config-xo-react-space` ?

**Comment by jamestalmage** [comment]
@zckrs the XO team believes [tabs are better](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/).

If you use XO to lint your tests, it allows you to [choose spaces over tabs](https://github.com/sindresorhus/xo#space) easily.

If you are using `eslint` directly and just using this as a shared config, I think you may need to fork.

**Comment by zckrs** [comment]
https://github.com/zckrs/eslint-config-xo-react-space

**Comment by kevva** [comment]
:+1:

**Comment by jamestalmage** [comment]
> Should we add this to the related section maybe?

Yes. @zckrs - can you make a PR adding it to the related section of the readme?
